language: ruby
bundler_args: --without kitchen_vagrant
rvm:
- 1.9.3
- 2.1
before_install:
- echo -n $EC2_KEY_CHUNK_{0..30} >> ~/.ssh/travis_ci_ec2.base64
- cat ~/.ssh/travis_ci_ec2.base64 | tr -d ' ' | base64 --decode > ~/.ssh/travis_ci_ec2.pem
- echo -n $EDB_KEY_CHUNK_{0..30} >> ~/encrypted_data_bag_secret.base64
- cat ~/encrypted_data_bag_secret.base64 | tr -d ' ' | base64 --decode > ~/encrypted_data_bag_secret
- echo -n $DEPLOY_KEY_CHUNK_{0..30} >> ~/.ssh/id_rsa.base64
- cat ~/.ssh/id_rsa.base64 | tr -d ' ' | base64 --decode > ~/.ssh/id_rsa
- chmod 600 ~/.ssh/travis_ci_ec2.pem ~/encrypted_data_bag_secret ~/.ssh/id_rsa
- bundle install
- bundle exec berks install
script:
- KITCHEN_LOG=debug bundle exec rake travis
after_script:
- bundle exec kitchen destroy
notifications:
  slack: evertrue:aceK52JFVEqyEyA82bWk2GKY
